---
title: "Frequently Asked Questions"
subtitle: "Answers to common questions"

html:
    theme: [litera, ../styles_html.scss]
---
## Unanswered Questions
If you have a question that is not answered here, please let me know by sending me an e-mail to [vlcek@beyondsimulations.com](mailto:vlcek@beyondsimulations.com?subject=ProgrammingEverydayDecisions) or by creating an issue on [GitHub](https://github.com/beyondsimulations/Programming-Everyday-Decisions/issues).

## Contribution and Mistakes
If you have found a mistake in the course material or if you have any suggestion on how to improve the course, please let me know by sending me an e-mail to [vlcek@beyondsimulations.com](mailto:vlcek@beyondsimulations.com?subject=ProgrammingEverydayDecisions) or by creating an issue on [GitHub](https://github.com/beyondsimulations/Programming-Everyday-Decisions/issues).

## FAQs

### How can I download PDF slides from the lecture?

1. First, open the lecture you want to download the slides from.
2. Then, click on the `RevealJS` button in the top right corner.
3. Now, click on the three stacked bars in the lower left corner.
4. Then, click on `Tools` in the upper left corner.
5. Now you can select `PDF Export Mode` and then save the slides as a PDF.
